2023-07-16 21:40:21,545 ERROR Internal Server Error: /news/ C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("'block' tag with name 'title' appears more than once"), <traceback object at 0x0000024343E14100>)
Traceback (most recent call last):
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
2023-07-16 21:40:21,592 ERROR "GET /news/ HTTP/1.1" 500 197190 C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-07-16 21:42:04,323 ERROR Internal Server Error: /news/ C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("'block' tag with name 'title' appears more than once"), <traceback object at 0x0000024343D03580>)
Traceback (most recent call last):
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
2023-07-16 21:42:04,363 ERROR "GET /news/ HTTP/1.1" 500 197364 C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-07-16 21:42:07,406 ERROR Internal Server Error: /news/ C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("'block' tag with name 'title' appears more than once"), <traceback object at 0x0000024343E40540>)
Traceback (most recent call last):
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
2023-07-16 21:42:07,428 ERROR "GET /news/ HTTP/1.1" 500 197364 C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-07-16 21:42:08,141 ERROR Internal Server Error: /news/ C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("'block' tag with name 'title' appears more than once"), <traceback object at 0x0000024343C6BD00>)
Traceback (most recent call last):
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
2023-07-16 21:42:08,187 ERROR "GET /news/ HTTP/1.1" 500 197354 C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-07-16 21:42:08,473 ERROR Internal Server Error: /news/ C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("'block' tag with name 'title' appears more than once"), <traceback object at 0x0000024343B4BE00>)
Traceback (most recent call last):
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
2023-07-16 21:42:08,496 ERROR "GET /news/ HTTP/1.1" 500 197364 C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-07-16 21:42:09,536 ERROR Internal Server Error: /news/ C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("'block' tag with name 'title' appears more than once"), <traceback object at 0x0000024343CEA300>)
Traceback (most recent call last):
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
2023-07-16 21:42:09,593 ERROR "GET /news/ HTTP/1.1" 500 197364 C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-07-16 21:42:17,731 ERROR Internal Server Error: /news/ C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("'block' tag with name 'title' appears more than once"), <traceback object at 0x0000024343DBD080>)
Traceback (most recent call last):
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
2023-07-16 21:42:17,759 ERROR "GET /news/ HTTP/1.1" 500 197374 C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-07-16 21:42:22,768 ERROR Internal Server Error: /news/ C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("'block' tag with name 'title' appears more than once"), <traceback object at 0x0000024343CC8940>)
Traceback (most recent call last):
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
2023-07-16 21:42:22,806 ERROR "GET /news/ HTTP/1.1" 500 197237 C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-07-16 21:46:40,642 ERROR Internal Server Error: /news/ C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("'block' tag with name 'title' appears more than once"), <traceback object at 0x0000024343D67680>)
Traceback (most recent call last):
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
2023-07-16 21:46:40,681 ERROR "GET /news/ HTTP/1.1" 500 197945 C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-07-16 21:53:16,724 ERROR Internal Server Error: /article/create/ C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('database is locked'), <traceback object at 0x00000243442131C0>)
Traceback (most recent call last):
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\News_Portal\news\views.py", line 79, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\views\generic\edit.py", line 135, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\forms\models.py", line 548, in save
    self.instance.save()
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\models\base.py", line 863, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\models\base.py", line 1006, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\models\base.py", line 1047, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
2023-07-16 21:53:22,886 ERROR Internal Server Error: /article/create/ C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\utils\log.py (<class 'kombu.exceptions.OperationalError'>, OperationalError('Error 11001 connecting to redis-18953.c302.asia-northeast1-1.gce.cloud.redislabs.com:18953. getaddrinfo failed.'), <traceback object at 0x00000243437A6E00>)
Traceback (most recent call last):
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\redis\connection.py", line 611, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\redis\connection.py", line 612, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\redis\connection.py", line 645, in _connect
    for res in socket.getaddrinfo(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\celery\backends\redis.py", line 119, in reconnect_on_error
    yield
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\celery\backends\redis.py", line 169, in _consume_from
    self._pubsub.subscribe(key)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\redis\client.py", line 1592, in subscribe
    ret_val = self.execute_command("SUBSCRIBE", *new_channels.keys())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\redis\client.py", line 1433, in execute_command
    self.connection = self.connection_pool.get_connection(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\redis\connection.py", line 1387, in get_connection
    connection.connect()
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\redis\connection.py", line 617, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 11001 connecting to redis-18953.c302.asia-northeast1-1.gce.cloud.redislabs.com:18953. getaddrinfo failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\redis\connection.py", line 611, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\redis\connection.py", line 612, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\redis\connection.py", line 645, in _connect
    for res in socket.getaddrinfo(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\kombu\connection.py", line 446, in _reraise_as_library_errors
    yield
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\celery\app\base.py", line 787, in send_task
    self.backend.on_task_call(P, task_id)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\celery\backends\redis.py", line 365, in on_task_call
    self.result_consumer.consume_from(task_id)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\celery\backends\redis.py", line 161, in consume_from
    return self.start(task_id)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\celery\backends\redis.py", line 139, in start
    self._consume_from(initial_task_id)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\celery\backends\redis.py", line 168, in _consume_from
    with self.reconnect_on_error():
  File "C:\Users\dimka\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\celery\backends\redis.py", line 122, in reconnect_on_error
    self._ensure(self._reconnect_pubsub, ())
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\celery\backends\redis.py", line 376, in ensure
    return retry_over_time(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\kombu\utils\functional.py", line 312, in retry_over_time
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\celery\backends\redis.py", line 106, in _reconnect_pubsub
    metas = self.backend.client.mget(self.subscribed_to)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\redis\commands\core.py", line 1893, in mget
    return self.execute_command("MGET", *args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\redis\client.py", line 1235, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\redis\connection.py", line 1387, in get_connection
    connection.connect()
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\redis\connection.py", line 617, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 11001 connecting to redis-18953.c302.asia-northeast1-1.gce.cloud.redislabs.com:18953. getaddrinfo failed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\News_Portal\news\views.py", line 79, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\views\generic\edit.py", line 135, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\forms\models.py", line 549, in save
    self._save_m2m()
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\forms\models.py", line 530, in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\models\fields\related.py", line 1966, in save_form_data
    getattr(instance, self.attname).set(data)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1152, in set
    self.add(*new_objs, through_defaults=through_defaults)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1070, in add
    self._add_items(
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1335, in _add_items
    signals.m2m_changed.send(
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
           ^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\News_Portal\news\signals.py", line 27, in notify_post_subscribe
    send_news_after_post.apply_async([instance.id], countdown=5)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\celery\app\task.py", line 575, in apply_async
    return app.send_task(
           ^^^^^^^^^^^^^^
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\celery\app\base.py", line 785, in send_task
    with P.connection._reraise_as_library_errors():
  File "C:\Users\dimka\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\dimka\Desktop\NewsPortal_D8.6.2-main\venv\Lib\site-packages\kombu\connection.py", line 450, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 11001 connecting to redis-18953.c302.asia-northeast1-1.gce.cloud.redislabs.com:18953. getaddrinfo failed.
